
#ifndef _TNA_ENGINE_PRIORITIES_H_
#define _TNA_ENGINE_PRIORITIES_H_ value

namespace tna
{

#define PRIORITY_INIT_TRANSFORM_MATRIX 1000000
#define PRIORITY_TRANSFORM_MATRIX_HIERARCHY 1000001
  
} /*  tna */ 
#endif /* ifndef _TNA_ENGINE_PRIORITIES_H_ */
